spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:uploads/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081
