spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
